apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: todoapp
spec:
  serviceAccountName: secrets-reader
  containers:
  - name: curl
    image: curlimages/curl:8.4.0
    command: ["sleep", "3600"]
